services:
  streamlit_app:
    build: .
    expose:
      - "8501"
    ports:
      - "8501:8501"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - .:/app  # Mount local directory to /app inside the container, optional
